name: Continuous Integration

'on':
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '12 3 * * 4'

jobs:
  ci:
    name: Continuous Integration
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        version: ['3.9', '3.11']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
          cache: 'pip'
      - name: Install build and test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable .[dev]
          pip install --editable .[test]
      - name: Install library stubs for mypy
        run: |
          make mypy-install-types
      - name: Install in "development mode"
        run: |
          pip install --editable .
      - name: Lint
        run: |
          make lint
      - name: Test
        env:
          PYTHONDEVMODE: 1
          PYTHONTRACEMALLOC: 1
        run: |
          make test
